# -*- coding: utf-8 -*-
"""Another copy of Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmu7bzrHhZHMi8GL7h-twFrEXwGLp27Q
"""

from google.colab import files
uploaded = files.upload()

import json
import pandas as pd
import matplotlib.pyplot as plt

# =====================================
# LOAD FILES AUTOMATICALLY (NO NAME ISSUES)
# =====================================
metrics_data = None
game_data = None

for filename in uploaded.keys():
    with open(filename, "r") as f:
        data = json.load(f)

        # Detect metrics file
        if "history" in data and "agent_records" in data:
            metrics_data = data
            print("Metrics file detected:", filename)

        # Detect game file
        if "detailed_steps" in data:
            game_data = data
            print("Game file detected:", filename)

# Safety check
if metrics_data is None:
    raise Exception("Metrics JSON not found")

if game_data is None:
    raise Exception("Game JSON not found")

# =====================================
# -------- PART 1: METRICS -------------
# =====================================
history_df = pd.DataFrame(metrics_data["history"])

trust_df = pd.DataFrame(history_df["trust_scores"].tolist())
trust_df["round"] = history_df["t"]

# 1. Trust Score
plt.figure()
for agent in ["B1", "B2", "B3"]:
    plt.plot(trust_df["round"], trust_df[agent], marker='o', label=agent)

plt.title("Trust Score Trend")
plt.legend()
plt.grid(True)
plt.show()

# 2. Error Propagation
plt.figure()
plt.plot(history_df["t"], history_df["error_propagation_rate"], marker='o')
plt.title("Error Propagation Trend")
plt.grid(True)
plt.show()

# 3. Final Score
agents = []
scores = []
for agent, rec in metrics_data["agent_records"].items():
    agents.append(agent)
    scores.append(rec["final_score"])

plt.figure()
plt.bar(agents, scores)
plt.title("Final Score by Agent")
plt.show()

# =====================================
# -------- PART 2: GAME DATA ----------
# =====================================
steps = game_data["detailed_steps"]

timesteps = [s["timestep"] for s in steps]
winning_rate = [s["winning_rate"] for s in steps]
threat_level = [s["threat_level"] for s in steps]

# 4. Winning Rate
plt.figure()
plt.plot(timesteps, winning_rate, marker='o')
plt.title("Winning Rate")
plt.grid(True)
plt.show()

# 5. Threat Level
plt.figure()
plt.plot(timesteps, threat_level, marker='o')
plt.title("Threat Level")
plt.grid(True)
plt.show()

print("All 5 plots generated successfully!")